services:
  - type: web
    name: psyh-trip
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run api
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: AUTH_TOKEN_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
