ALTER TABLE wiki_articles
ADD COLUMN IF NOT EXISTS hp INTEGER,
ADD COLUMN IF NOT EXISTS stamina INTEGER,
ADD COLUMN IF NOT EXISTS strength INTEGER,
ADD COLUMN IF NOT EXISTS dexterity INTEGER,
ADD COLUMN IF NOT EXISTS intelligence INTEGER,
ADD COLUMN IF NOT EXISTS charisma INTEGER;
